apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsentinels.bluglio.com
spec:
  scope: Cluster
  conversion:
    strategy: None
  group: bluglio.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          secrets:
            type: array
            items:
              type: string
          podSelector:
            type: object
            description: "Label selector used for selecting Pods"
            additionalProperties:
              type: string
          namespaces:
            type: array
            items:
              type: string
  names:
    kind: SecretSentinel
    singular: secretsentinel
    plural: secretsentinels
    shortNames:
    - ss
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-sentinel-crd
rules:
- apiGroups:
  - bluglio.com
  resources:
  - configmonitor
  - configmonitor/finalizers
  verbs: [ get, list, create, update, delete, deletecollection, watch ]